DROP TABLE IF EXISTS `refitemdata`;
CREATE TABLE  `refitemdata` (
	`refID` int(11) NOT NULL,
	`ItemName` varchar(120) NOT NULL,
	`KoreanName` varchar(120) NOT NULL,
	`refBaseName` varchar(120) NOT NULL,
	`refResName` varchar(120) NOT NULL,
	`refDescName` varchar(120) NOT NULL,
	`Type1` int(1) NOT NULL,
	`Type2` int(1) NOT NULL,
	`Type3` int(1) NOT NULL,
	`Type4` int(1) NOT NULL,
	`Type5` int(1) NOT NULL,
	`Type6` int(1) NOT NULL,
	`SpawnTimeout` INTEGER NOT NULL,
	`Race` INTEGER(1) NOT NULL,
	`SoxType` INTEGER(1) NOT NULL,

TODO:

	`StoreFeed` int(11) NOT NULL,
	`SellPrice` int(11) NOT NULL,
	`Requirement1` int(11) NOT NULL,
	`RequirementLv1` int(11) NOT NULL,
	`Requirement2` int(11) NOT NULL,
	`RequirementLv2` int(11) NOT NULL,
	`Requirement3` int(11) NOT NULL,
	`RequirementLv3` int(11) NOT NULL,
	`Requirement4` int(11) NOT NULL,
	`RequirementLv4` int(11) NOT NULL,
	`QSP` int(11) NOT NULL,

TODO:

	`Model` varchar(120) NOT NULL,
	`DropModel` varchar(120) NOT NULL,
	`Icon` varchar(120) NOT NULL,
	`GP` varchar(20) NOT NULL,
	
TODO:

	`MaxStack` int(3) NOT NULL,
	`Gender` int(1) NOT NULL,

TODO:

	`degree` int(2) not null,
	`min_dura` int(11) NOT NULL,
	`max_dura` int(11) NOT NULL,
	`min_pd` float NOT NULL,
	`max_pd` float NOT NULL,
	`pd_lv` float NOT NULL,

TODO:

	`min_pa` float NOT NULL,
	`max_pa` float NOT NULL,
	`pa_lv` float NOT NULL,
	`min_br` int(2) NOT NULL,
	`max_br` int(2) NOT NULL,
	`min_md` float NOT NULL,
	`max_md` float NOT NULL,
	`md_lv` float NOT NULL,
	`min_ma` float NOT NULL,
	`max_ma` float NOT NULL,
	`ma_lv` float NOT NULL,
	`pd_reinf` int(11) NOT NULL,
	`pr` int(11) NOT NULL,
	`md_reinf` int(11) NOT NULL,
	`atk_dist` int(11) NOT NULL,
	`min_low_patk` int(11) NOT NULL,
	`max_low_patk` int(11) NOT NULL,
	`min_high_patk` int(11) NOT NULL,
	`max_high_patk` int(11) NOT NULL,
	`phy_atk_lv` float NOT NULL,
	`min_low_matk` int(11) NOT NULL,
	`max_low_matk` int(11) NOT NULL,
	`min_high_matk` int(11) NOT NULL,
	`max_high_matk` int(11) NOT NULL,
	`mag_atk_lv` float NOT NULL,
	`min_low_phy_reinf` int(11) NOT NULL,
	`max_low_phy_reinf` int(11) NOT NULL,
	`min_high_phyref` int(11) NOT NULL,
	`max_high_phyref` int(11) NOT NULL,
	`min_low_magref` int(11) NOT NULL,
	`max_low_magref` int(11) NOT NULL,
	`min_high_magref` int(11) NOT NULL,
	`max_high_magref` int(11) NOT NULL,
	`min_ar` int(11) NOT NULL,
	`max_ar` int(11) NOT NULL,
	`min_crit` int(2) NOT NULL,
	`max_crit` int(2) NOT NULL,
	`effect1` int(11) NOT NULL,
	`arg1` VARCHAR(120) NOT NULL,
	`effect2` int(11) NOT NULL,
	`arg2` VARCHAR(120) NOT NULL,
	`effect3` int(11) NOT NULL,
	`arg3` VARCHAR(120) NOT NULL,
	`effect4` int(11) NOT NULL,
	`arg4` VARCHAR(120) NOT NULL,
	`effect5` int(11) NOT NULL,
	`arg5` VARCHAR(120) NOT NULL,
	`effect6` int(11) NOT NULL,
	`arg6` VARCHAR(120) NOT NULL,
	`effect7` INTEGER NOT NULL,
	`effect8` INTEGER NOT NULL,
	`effect9` INTEGER NOT NULL,
	`effect10` INTEGER NOT NULL,
	`max_attr_count` int(11) NOT NULL,
	`avatar_flag` int(1) NOT NULL,
	PRIMARY KEY (`refID`)
);
