DROP TABLE IF EXISTS `refshopgoods`;
CREATE TABLE `refshopgoods` (
	`EntryFlag` INTEGER(1) NOT NULL,
	`ItemFlag` INTEGER(1) NOT NULL,
	`Tab` VARCHAR(50) NOT NULL,
	`PKItem` VARCHAR(60) NOT NULL,
	`Position` INTEGER NOT NULL,
	`E1` INTEGER(1) NOT NULL,
	`ES1` VARCHAR(3) NOT NULL,
	`E2` INTEGER(1) NOT NULL,
	`ES2` VARCHAR(3) NOT NULL,
	`E3` INTEGER(1) NOT NULL,
	`ES3` VARCHAR(3) NOT NULL,
	`E4` INTEGER(1) NOT NULL,
	`ES4` VARCHAR(3) NOT NULL
);
	
