DROP TABLE IF EXISTS `refshopgroup`;
CREATE TABLE `refshopgroup` (
	`EntryFlag` INTEGER(1) NOT NULL,
	`ItemFlag` INTEGER(1) NOT NULL,
	`ID` INTEGER NOT NULL,
	`Group` VARCHAR(50) NOT NULL,
	`NPC` VARCHAR(50) NOT NULL,
	`EmptyID1` INTEGER(1) NOT NULL,
	`EmptyNCP1` VARCHAR(3) NOT NULL,
	`EmptyID2` INTEGER(1) NOT NULL,
	`EmptyNCP2` VARCHAR(3) NOT NULL,
	`EmptyID3` INTEGER(1) NOT NULL,
	`EmptyNCP3` VARCHAR(3) NOT NULL,
	`EmptyID4` INTEGER(1) NOT NULL,
	`EmptyNCP4` VARCHAR(3) NOT NULL,
	PRIMARY KEY (`ID`)
);

