/*********************************************************************************
 *
 * This file is part of eSRO.
 *
 * eSRO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * eSRO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright ⓒ 2013  Rafael Dominguez (npcdoom)
 *
 *********************************************************************************/

#ifndef __SLES_GAME_SERVER_CLIENT_OPCODES_HPP__
#define __SLES_GAME_SERVER_CLIENT_OPCODES_HPP__

enum
{
    CLIENT_LOGIN = 0x6103,

    CLIENT_LOBBY = 0x703A,
    CLIENT_LOBBY_SELECT = 0x72EE,

    CLIENT_GAME_LOGIN = 0x36CF,
    CLIENT_GAME_LOGOUT = 0x744E,
    CLIENT_GAME_LOGOUT_CANCEL = 0x7413,

    CLIENT_PLAYER_MOVEMENT = 0x7674,
    CLIENT_PLAYER_TRANSLATE = 0x7477,
    CLIENT_PLAYER_ROTATE = 0x74E4,
    CLIENT_PLAYER_CHAT = 0x7576,
    CLIENT_PLAYER_HELP_ICON = 0x71AD,
    CLIENT_PLAYER_EMOTE = 0x33F8,
    CLIENT_PLAYER_SELECT_TARGET = 0x7445,
    CLIENT_PLAYER_ACTION = 0x70F0,
    CLIENT_PLAYER_SETTING = 0x7611,
    CLIENT_PLAYER_RESURRECT = 0x34C9,
    CLIENT_PLAYER_MOVEMENT_STATE = 0x76B3,
    CLIENT_PLAYER_BLOCK = 0x7195,
    CLIENT_PLAYER_USE_STORAGE = 0x7711,
    CLIENT_PLAYER_CAST_BERSERK = 0x7436,
    CLIENT_PLAYER_INVITE_ANSWER = 0x368B,

    CLIENT_STATS_INT_INC = 0x724A,
    CLIENT_STATS_STR_INC = 0x71D0,

    CLIENT_MASTERY_INC = 0x70A0,
    CLIENT_SKILL_INC = 0x779D,
    CLIENT_SKILL_MASTERY_EDIT = 0x765F,

    CLIENT_STALL_CREATE = 0x7036,
    CLIENT_STALL_ACTION = 0x7783,
    CLIENT_STALL_CLOSE = 0x73D8,
    CLIENT_STALL_ENTER = 0x70BE,
    CLIENT_STALL_LEAVE = 0x7028,
    CLIENT_STALL_BUY = 0x7494,
    CLIENT_STALL_NETWORK_SEARCH = 0x70F5,
    CLIENT_STALL_NETWORK_PURCHASE = 0x7663,

    CLIENT_PARTY_FORM = 0x73EE,
    CLIENT_PARTY_SEARCH = 0x77EE,
    CLIENT_PARTY_INFORMATION = 0x76D4,
    CLIENT_PARTY_REMOVE = 0x7010,
    CLIENT_PARTY_CHANGE = 0x72BA,
    CLIENT_PARTY_JOIN = 0x776F,
    CLIENT_PARTY_CREATE = 0x74F8,
    CLIENT_PARTY_LEADER = 0x73A9,
    CLIENT_PARTY_KICK = 0x7170,
    CLIENT_PARTY_LEAVE = 0x7465,
    CLIENT_PARTY_INVITE = 0x7442,
    CLIENT_PARTY_ANSWER = 0x3040,

    CLIENT_TALK_INITIATE = 0x74F2,
    CLIENT_TALK_TERMINATE = 0x770C,

    CLIENT_TELEPORT_DESIGNATE = 0x7228,
    CLIENT_TELEPORT_REQUEST = 0x73AF,
    CLIENT_TELEPORT = 0x32E7,
    CLIENT_TELEPORT_CANCEL = 0x70F4,

    CLIENT_ITEM_MOVE = 0x73CF,
    CLIENT_ITEM_REPAIR = 0x73DA,
    CLIENT_ITEM_USE = 0x754B,
    CLIENT_ITEM_BUY_BACK = 0x70AF,
    CLIENT_ITEM_AVATAR_MAGICOPTION = 0x35CF,

    CLIENT_TRANSPORT_MOVEMENT = 0x749B,
    CLIENT_TRANSPORT_ACTION = 0x75A5,
    CLIENT_TRANSPORT_TERMINATE = 0x7779,

    CLIENT_ALCHEMY_DISJOINT = 0x77B6,
    CLIENT_ALCHEMY_DISMANTLE = 0x7007,
    CLIENT_ALCHEMY_ENCHANT = 0x7403,
    CLIENT_ALCHEMY_MAGICOPTS = 0x7290,

    CLIENT_GUILD_CREATE = 0x7591,
    CLIENT_GUILD_DONATE_GP = 0x74A0,
    CLIENT_GUILD_NOTICE = 0x72B0,
    CLIENT_GUILD_POSITION_ALLOCATION = 0x70B6,
    CLIENT_GUILD_AUTHORITY = 0x768A,
    CLIENT_GUILD_GRANTNAME = 0x74E6,
    CLIENT_GUILD_WITHDRAW = 0x75FB,
    CLIENT_GUILD_PROMOTE = 0x7553,
    CLIENT_GUILD_LEADER_VOTE = 0x705E,
    CLIENT_GUILD_LEADER_TRANSFER = 0x77E8,
    CLIENT_GUILD_STORAGE_OPEN = 0x7680,
    CLIENT_GUILD_STORAGE_INFO = 0x71C1,
    CLIENT_GUILD_STORAGE_CLOSE = 0x7001,
    CLIENT_GUILD_INVITE = 0x74D8,
    CLIENT_GUILD_LEAVE = 0x7508,
    CLIENT_GUILD_WAR_PROPOSE = 0x7490,
    CLIENT_GUILD_WAR_REWARD_GOLD = 0x7133,
    CLIENT_GUILD_DISBAND = 0x7720,

    CLIENT_ALLIANCE_INVITE = 0x7080,
    CLIENT_ALLIANCE_EXPEL = 0x7025,
    CLIENT_ALLIANCE_SECEDE = 0x7725,

    CLIENT_EXCHANGE_REQUEST = 0x77F2,
    CLIENT_EXCHANGE_CLOSE = 0x7066,
    CLIENT_EXCHANGE_CONFIRM = 0x7207,
    CLIENT_EXCHANGE_APPROVE = 0x745C,

    CLIENT_FRIEND_REQUEST = 0x734A,
    CLIENT_FRIEND_DELETE = 0x7199,
    CLIENT_FRIEND_ANSWER = 0x35C9,
    CLIENT_FRIEND_GROUP_CREATE = 0x7270,
    CLIENT_FRIEND_GROUP_DELETE = 0x760E,
    CLIENT_FRIEND_GROUP_ENTRY_ADD = 0x74B3,

    CLIENT_MESSAGE_SEND = 0x74D6,
    CLIENT_MESSAGE_BROADCAST = 0x7743,
    CLIENT_MESSAGE_READ = 0x7216,
    CLIENT_MESSAGE_DELETE = 0x713B,

    CLIENT_JOB_JOIN = 0x7126,
    CLIENT_JOB_PAST_INFO = 0x7342,
    CLIENT_JOB_ALIAS = 0x752C,
    CLIENT_JOB_RANKING = 0x7128,
    CLIENT_JOB_PAYMENT = 0x77BF,
    CLIENT_JOB_LEAVE  = 0x71EF,
    CLIENT_JOB_PRODUCT_INFORMATION = 0x7551,

    CLIENT_ACADEMY_LIST = 0x77A7,
    CLIENT_ACADEMY_NOTICE = 0x7C53,
    CLIENT_ACADEMY_REMOVE = 0x74A7,
    CLIENT_ACADEMY_REQUEST = 0x7060,
    CLIENT_ACADEMY_FORM = 0x72C9,
    CLIENT_ACADEMY_CHANGE = 0x728B,
    CLIENT_ACADEMY_ESTABLISH = 0x77BB,
    CLIENT_ACADEMY_DISBAND = 0x7375,
    CLIENT_ACADEMY_RANK = 0x720B,       //HONOR RANK

    CLIENT_TUTORIAL_REQUEST = 0x7481,
    CLIENT_EVENT_CALENDAR = 0x7009,

    CLIENT_GM_COMMAND = 0x726D,

    CLIENT_FORTRESS_APPLY = 0x77C6,
    CLIENT_FORTRESS_RETURN = 0x7521
};

#endif //__SLES_GAME_SERVER_CLIENT_OPCODES_HPP__
