/*********************************************************************************
 *
 * This file is part of eSRO.
 *
 * eSRO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * eSRO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright ⓒ 2013  Rafael Dominguez (npcdoom)
 *
 *********************************************************************************/

#ifndef __SRNL_GAME_SERVER_OPCODES_HPP__
#define __SRNL_GAME_SERVER_OPCODES_HPP__

enum
{
    SERVER_SHARD_LOGIN = 0xA103,

    SERVER_LOBBY = 0xB03A,
    SERVER_LOBBY_SELECT = 0xB2EE,

    SERVER_LOGOUT = 0xB44E,
    SERVER_LOGOUT_NOTIFY = 0x360B,
    SERVER_LOGOUT_CANCEL = 0xB413,

    SERVER_WEATHER_NOTIFY = 0x3B9D,

    SERVER_PLAYER_INFO_BEGIN = 0x33E8,
    SERVER_PLAYER_INFO_END = 0x3750,
    SERVER_PLAYER_INFO = 0x3024,
    SERVER_PLAYER_STATS = 0x369C,
    SERVER_PLAYER_ID = 0x3064,			//I THINK THIS PACKET DISPLAY THE SUN POSITION (WORLD TIME)
    SERVER_PLAYER_EXTRA_STATS = 0x3213, ///GOLD, SP AND BERSERK GAUGE
    SERVER_PLAYER_ROTATE = 0xB4E4,
    SERVER_PLAYER_MSG = 0x326E,
    SERVER_PLAYER_MSG_ACK = 0xB576,
    SERVER_PLAYER_ACTION = 0xB0F0,
    SERVER_PLAYER_SELECT_TARGET = 0xB445,
    SERVER_PLAYER_HELP_ICON = 0xB1AD,
    SERVER_PLAYER_EMOTE = 0x33F8,
    SERVER_PLAYER_PICKUP = 0x3138,
    SERVER_PLAYER_XP_SP = 0x31B4,
    SERVER_PLAYER_LEVELUP_ANIMATION = 0x325E,
    SERVER_PLAYER_GUILD = 0x30B6,
    SERVER_PLAYER_GUILD_GRANTNAME = 0x34E6,
    SERVER_PLAYER_SILK = 0x33B6,
    SERVER_PLAYER_STATUS = 0x36A5,
    SERVER_PLAYER_DEATH = 0x3709,
    SERVER_PLAYER_INVENTORY_SLOTS = 0x30B7,

    SERVER_STORAGE_GOLD = 0x374F,
    SERVER_STORAGE_ITEMS = 0x33F2,
    SERVER_STORAGE_ENTER = 0x36AE,

    SERVER_INC_STR = 0xB1D0,
    SERVER_INC_INT = 0xB24A,

    SERVER_MULTI_SPAWN_BEGIN = 0x37D1,
    SERVER_MULTI_SPAWN = 0x36B7,
    SERVER_MULTI_SPAWN_END = 0x377E,
    SERVER_SINGLE_SPAWN = 0x35C8,
    SERVER_SINGLE_DESPAWN = 0x3183,

    SERVER_NPC_MOVEMENT = 0xB674,
    SERVER_ENTITY_UPDATE_POSITION = 0x302E,
    SERVER_HPMP = 0x33AE,
    SERVER_UPDATE_SPEED = 0x365E,
    SERVER_UPDATE_STATE = 0x3304,
    SERVER_STATUS_DAMAGE = 0x347F,

    SERVER_SEND_INVITATION = 0x368B,

    SERVER_NPC_TALK_INITIATE = 0xB4F2,
    SERVER_NPC_TALK_TERMINATE = 0xB70C,

    SERVER_TELEPORT_ZONE = 0x37D5,
    SERVER_TELEPORT_DESIGNATE = 0xB228,
    SERVER_TELEPORT_TO_DESTINATION = 0xB3AF,

    SERVER_ACTION_INFORMATION = 0xB083,
    SERVER_DELAY_ACTION_INFORMATION = 0xB5B5,

    SERVER_MASTERY_INCREASE = 0xB0A0,

    SERVER_SKILL_INCREASE = 0xB79D,
    SERVER_SKILL_INIT_BUFF = 0xB258,
    SERVER_SKILL_BUFF_TIMEOUT = 0x35B0,
    SERVER_SKILL_TERMINATE_BUFF = 0xB4C3,

    SERVER_UNIQUE_MSG = 0x3588,

    SERVER_ITEM_MOVEMENT = 0xB3CF,
    SERVER_ITEM_STRENGTHEN = 0xB403,
    SERVER_ITEM_EQUIP = 0x3220,
    SERVER_ITEM_UNEQUIP = 0x37D3,
    SERVER_ITEM_EQUIP_WAIT = 0x31A6,
    SERVER_ITEM_EQUIP_WAIT_CANCEL = 0x34BD,
    SERVER_ITEM_AVATAR_MAGIC_OPTION = 0x3712,
    SERVER_ITEM_DURABILITY = 0x31C4,
    SERVER_ITEM_REPAIR = 0xB3DA,
    SERVER_ITEM_USE = 0xB54B,
    SERVER_ITEM_ANIMATION = 0x34F1,
    SERVER_ITEM_QUANTITY_NOTIFY = 0x32A5,
    SERVER_ITEM_STONE_CREATE = 0x358F,
    SERVER_ITEM_MAGIC_OPTION_NOTIFY = 0xB403,
    SERVER_ITEM_RONDO = 0x352B,
    SERVER_ITEM_DROP = 0x375C,
    SERVER_ITEM_AMMO = 0x304A,

    SERVER_TRANSPORT_STATS = 0x3106,
    SERVER_TRANSPORT_ACTION = 0xB5A5,
    SERVER_TRANSPORT_TERMINATE = 0xB779,
    SERVER_TRANSPORT_STATS_REMOVE = 0x34E8,

    SERVER_NOTIFY_TRANSPORT_OPERATION = 0x3092,

    SERVER_STALL_OPEN = 0xB036,
    SERVER_STALL_SPAWN = 0x332A,
    SERVER_STALL_DESPAWN = 0x3387,
    SERVER_STALL_ACTION = 0xB783,
    SERVER_STALL_NAME = 0x33CD,
    SERVER_STALL_ENTER = 0xB0BE,
    SERVER_STALL_LEAVE = 0xB028,
    SERVER_STALL_BUY = 0xB494,
    SERVER_STALL_NOTIFY = 0x373B,
    SERVER_STALL_CLOSE = 0xB3D8,
    SERVER_STALL_NETWORK_SEARCH = 0xB0F5,
    SERVER_STALL_NETWORK_PURCHASE = 0xB663,

    SERVER_EXCHANGE_ITEM = 0x336F,
    SERVER_EXCHANGE_GOLD = 0x37A9,
    SERVER_EXCHANGE_CONFIRM = 0xB207,
    SERVER_EXCHANGE_PLAYER_CONFIRMED = 0x35BB,
    SERVER_EXCHANGE_APPROVE = 0xB45C,
    SERVER_EXCHANGE_COMPLETED = 0x33E6,
    SERVER_EXCHANGE_INIT_CLOSE = 0x3637,
    SERVER_EXCHANGE_END_CLOSE = 0xB066,
    SERVER_EXCHANGE_ACCEPT = 0x3411,
    SERVER_EXCHANGE_ACCEPTED = 0xB7F2,

    SERVER_PARTY_FORM = 0xB3EE,
    SERVER_PARTY_INFORMATION = 0xB6D4,
    SERVER_PARTY_DELETE = 0xB010,
    SERVER_PARTY_CHANGE = 0xB2BA,
    SERVER_PARTY_LIST = 0xB7EE,
    SERVER_PARTY_INVITE = 0xB442,
    SERVER_PARTY_ANSWER = 0xB76F,
    SERVER_PARTY_INVITE_ANSWER = 0xB652,
    SERVER_PARTY_REQUEST = 0x776F,
    SERVER_PARTY_INFO = 0x300A,
    SERVER_PARTY_UPDATE = 0x3AEF, // // //
    SERVER_PARTY_BANNED = 0xB4C3,

    SERVER_FRIEND_LIST = 0x37ED,
    SERVER_FRIEND_NOTIFY = 0x3957,
    SERVER_FRIEND_DELETE = 0xB199,
    SERVER_FRIEND_REQUEST = 0x734A,
    SERVER_FRIEND_ANSWER = 0xB34A,
    SERVER_FRIEND_GROUP_CREATE = 0xB270,
    SERVER_FRIEND_GROUP_DELETE = 0xB60E,
    SERVER_FRIEND_GROUP_ENTRY_ADD = 0xB4B3,

    SERVER_BLOCK = 0xB195,

    SERVER_MESSAGE_BROADCAST = 0xB1C1,
    SERVER_MESSAGE_SEND = 0xB4D6,
    SERVER_MESSAGE_RECEIVE = 0x3957,
    SERVER_MESSAGE_READ = 0xB216,
    SERVER_MESSAGE_DELETE = 0xB13B,

    SERVER_FORTRESS_INFO = 0x3C97,

    SERVER_JOB_JOIN = 0xB126,
    SERVER_JOB_ALIAS = 0xB52C,
    SERVER_JOB_PAST_INFO = 0xB342,
    SERVER_JOB_RANKING = 0xB128,
    SERVER_JOB_PAYMENT = 0xB7BF,
    SERVER_JOB_LEAVE = 0xB1EF,
    SERVER_JOB_PRODUCT_INFORMATION = 0xB551,
    SERVER_JOB_TRADE_SCALE = 0x3092,
    SERVER_JOB_TRADE_STATE = 0x35BE,
    SERVER_JOB_XP = 0x3342,

    SERVER_GUILD_CREATE = 0xB591,
    SERVER_GUILD_JOIN = 0xB5B6,
    SERVER_GUILD_INFO = 0x35CD,
    SERVER_GUILD_INFO_BEGIN = 0x3250,
    SERVER_GUILD_INFO_END = 0x30FA,
    SERVER_GUILD_NOTICE = 0xB2B0,
    SERVER_GUILD_NOTIFY = 0x393F,
    SERVER_GUILD_DISBAND = 0xB720,
    SERVER_GUILD_DONATE_GP = 0xB4A0,
    SERVER_GUILD_PROMOTE = 0xB553,
    SERVER_GUILD_AUTHORITY = 0xB68A,
    SERVER_GUILD_POSITION = 0xB0B6,
    SERVER_GUILD_KICK = 0xB5FB,
    SERVER_GUILD_GRANT = 0xB4E6,
    SERVER_GUILD_LEAVE = 0xB508,
    SERVER_GUILD_CLEAR = 0x31DD,
    SERVER_GUILD_WAR_INVITE = 0xB490,
    SERVER_GUILD_TRANSFER_LEADERSHIP = 0xB7E8,
    SERVER_GUILD_STORAGE_OPEN = 0xB680,
    SERVER_GUILD_STORAGE_CLOSE = 0xB001,
    SERVER_GUILD_STORAGE_GOLD = 0x30A6,
    SERVER_GUILD_STORAGE_ITEM = 0x3261,
    SERVER_GUILD_STORAGE_END = 0x3311,
    SERVER_GUILD_INVITE_DENY = 0xB5B6,
    SERVER_GUILD_INVITE_DENIED = 0xB4D8,
    SERVER_GUILD_INVITE_ERROR = 0xB4D8,
    SERVER_GUILD_UNION_INVITE = 0xB490,

    SERVER_ALLIANCE_LIST = 0x3313,
    SERVER_ALLIANCE_EXPEL = 0xB025,
    SERVER_ALLIANCE_SECEDE = 0xB725,

    SERVER_ACADEMY_LIST = 0xB4A7,
    SERVER_ACADEMY_NOTICE = 0xB631,
    SERVER_ACADEMY_NOTIFY = 0xB4D4,
    SERVER_ACADEMY_CHANGE = 0xB2C9,
    SERVER_ACADEMY_FORM = 0xB333,
    SERVER_ACADEMY_REQUEST = 0xB7A7,
    SERVER_ACADEMY_REMOVE = 0xB28B,
    SERVER_ACADEMY_INFO = 0xB24D,
    SERVER_ACADEMY_ERROR = 0xB77B,
    SERVER_ACADEMY_DISBAND = 0xB195,

    SERVER_TUTORIAL_RESPONSE = 0xB481
};

#endif //__SRNL_GAME_SERVER_OPCODES_HPP__
